<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Mage
 * @package    Mage_ManualCardPayment
 * @copyright  Copyright (c) 2008 Andrej Sinicyn, Mik3e
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
        <li>
            <div class="input-box">
                <?php if ($this->getMethod()->getCustomText()): ?>
                    <?php echo $this->getMethod()->getCustomText() ?><br />
                <?php endif; ?>
            </div>
        </li>
    </ul>
</fieldset>
