<script type="text/javascript"
	src="<?php echo $this->getJsUrl('jQuery/jquery-1.7.js'); ?>"></script>
<script type="text/javascript"
	src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.7/jquery-ui.js"></script>
<link
	type="text/css" rel="Stylesheet"
	href="http://ajax.microsoft.com/ajax/jquery.ui/1.8.5/themes/smoothness/jquery-ui.css" />
<script type="text/javascript">
jQuery.noConflict();
jQuery(document).ready
(
	function()
	{
        var dates = jQuery("#from, #to").datepicker(
                {
                    defaultDate : "-1m",
                    changeMonth : true,
                    numberOfMonths : 1,
                    dateFormat: 'yy-mm-dd',
                    onSelect : function(selectedDate)
                    {
	                    var option = this.id == "from" ? "minDate" : "maxDate", instance = jQuery(this).data(
	                            "datepicker"), date = jQuery.datepicker.parseDate(instance.settings.dateFormat
	                            || jQuery.datepicker._defaults.dateFormat, selectedDate, instance.settings);
	                    dates.not(this).datepicker("option", option, date);
                    }
                });
	}
);
</script>

<p>Leaving from or to blank will mean there are no limits and all
	records will be included.</p>
<form action="<?php echo $this->getUrl('*/*/downloadPricing'); ?>">
	<label for="from">From</label><input id="from" name="from" type="text" />
	<br> <label for="to">To</label><input id="to" name="to" type="text" />
	<br>
	<button>Download .csv</button>
</form>
